# version: "3.9"

services:
  app:
    image: rag-based-notes-helper
    build: .
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
      HF_HOME: /root/.cache/huggingface
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./hf_cache:/root/.cache/huggingface
    stdin_open: true
    tty: true
