# version: "3.9"

services:
  rag-app:
    image: ghcr.io/stevenhuang41/rag-based-notes-helper:latest
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
      HF_HOME: /root/.cache/huggingface
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./hf_cache:/root/.cache/huggingface
    stdin_open: true
    tty: true
